name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: '30 03 01 */3 *' # Artifacts expire every 3 months

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        sm_version:
          - "1.11"

        mm_version:
          - "1.11"

        include:
          - mm_version: "1.11"
            mm_branch: "1.11-dev"

          - sm_version: "1.11"
            sm_branch: "1.11-dev"

          - os: ubuntu-latest
            os_short: linux

    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Checking out SourceMod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive

      - name: Checking out MM:Source
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: ${{ matrix.mm_branch }}
          path: metamod-${{ matrix.mm_version }}

      - name: Checking out AMBuild
        uses: actions/checkout@v2
        with:
          repository: accelerator74/ambuild
          path: ambuild

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setting up ambuild
        working-directory: ambuild
        run: python setup.py install

      - name: Checking out hl2sdk-l4d2
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d2
          path: ambuild/hl2sdk-l4d2

      - name: Checking out hl2sdk-sdk2013
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: sdk2013
          path: ambuild/hl2sdk-sdk2013

      - name: Checking out hl2sdk-tf2
        uses: actions/checkout@v2
        with:
          repository: brysondev/hl2sdk
          ref: tf2
          path: ambuild/hl2sdk-tf2

      - name: Checking out hl2sdk-csgo
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: csgo
          path: ambuild/hl2sdk-csgo

      - name: Checking out own repository
        uses: actions/checkout@v2
        with:
          path: autocomplete

      - name: Compiling Srcds-Autocomplete files
        run: |
          mkdir build
          cd build
          python ../configure.py --enable-optimize -s present --hl2sdk-root "${{ github.workspace }}/ambuild" --sm-path="${{ github.workspace }}/sourcemod-${{ matrix.sm_version }}" --mms-path="${{ github.workspace }}/metamod-${{ matrix.mm_version }}"
          ambuild

      - name: Uploading package
        uses: actions/upload-artifact@v2
        with:
          name: autocomplete-sm${{ matrix.sm_version }}-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: autocomplete/build/package
